task #87 - ci: Added CI workflow
ISPP-Eventia/eventus pull request #105
Opened 2022-03-14 15:23 UTC by carvilgar1

workflow must be in the main branch to be triggered

2022-03-14 17:05 UTC, laur2000 requested changes

2022-03-14 17:05 UTC, laur2000 commented on .github/workflows/eventus-cicd.yml
> +        npm test
Los tests se ejecutan con el comando `npm run test`

2022-03-14 20:20 UTC, JSnow11 requested changes
## Review
- added some comments about workflow triggers
- we can also add the codacy report, I'm creating a secret named `CODACY_KEY`

2022-03-15 01:02 UTC, carvilgar1 commented
This branch should also be merged with develop

2022-03-16 17:44 UTC, carvilgar1 commented
![image](https://user-images.githubusercontent.com/72742676/158653941-6be48480-4ba1-4bec-bdbe-1e4628e1737c.png)
Now working with java

2022-03-16 17:51 UTC, carvilgar1 commented
![image](https://user-images.githubusercontent.com/72742676/158655232-31c9796a-fc12-41bf-a1ec-6132f98f80f1.png)
![image](https://user-images.githubusercontent.com/72742676/158655426-7d78d0bd-838c-498c-a30d-7be819e2f88a.png)

Now the whole project is covered

2022-03-18 16:01 UTC, JSnow11 approved these changes
## Review
ready to be merged

2022-03-19 21:48 UTC, laur2000 approved these changes

2022-03-19 21:48 UTC, merged