Feature/#73 tickets participation
ISPP-Eventia/eventus pull request #161
Opened 2022-03-21 18:42 UTC by josrompoz1

close #73

  ## changes
  - Added the ticket endpoint.
  - Added autogenerate ticket pdf.

  ## steps to review
  - POST request for create a participation (/participations) with json {"eventId:1"}
  - GET request for obtain the PDF (/participation/{id_participation}/ticket)
  - With Postman can´t see the pdf's content. Try the requests with Insomnia
  
  ## concerns
  - Must have a event created
  - Must have a user created

2022-03-21 21:29 UTC, pedalopon requested changes

2022-03-21 21:29 UTC, pedalopon commented on backend/src/main/java/com/eventus/backend/controllers/ParticipationController.java
> +                document = this.participationService.insertImageInPDF(document, "src/main/resources/com.eventus.backend.controllers/Logo.png");
PdfGeneration logic should be in participationService

2022-03-21 21:40 UTC, pabgonmon2 commented
Codacy warnings should be resolved before merge.

2022-03-21 21:41 UTC, pabgonmon2 requested changes
Codacy warnings should be resolved before merge.

2022-03-22 18:05 UTC, pabgonmon2 approved these changes

2022-03-22 18:05 UTC, merged