Feature/#144 session endpoints
ISPP-Eventia/eventus pull request #213
Opened 2022-03-29 17:24 UTC by pedalopon

## Review 
Implemented login and signup endpoints

## Insonimia collection
https://drive.google.com/file/d/1IBbnKYEPX6KlSEsogryw36IkA4sWJ2gB/view?usp=sharing

2022-03-29 17:33 UTC, josaloroc approved these changes
It seems that everything is correct

2022-03-30 05:52 UTC, laur2000 requested changes

2022-03-30 05:52 UTC, laur2000 commented on frontend/src/api/axios.ts
Haría falta añadir el token a todas las peticiones

2022-03-30 05:52 UTC, laur2000 commented on frontend/src/pages/session/session.tsx
> +      localStorage.setItem("userId", r.data.id);
Deberíamos coger el token y guardarlo tambien en el localStorage

2022-03-30 13:56 UTC, pedalopon commented on backend/src/main/java/com/eventus/backend/configuration/TokenAuthenticationFilter.java
> +        final Authentication auth = new UsernamePasswordAuthenticationToken(token, token);
Funciona así debido a que el retriveUser trae los userDetails a partir del token y no del username

2022-03-30 16:28 UTC, JSnow11 commented on frontend/src/pages/session/session.tsx
> +      localStorage.setItem("userId", r.data.id);
Si pero ahora lo hacemos por interceptor, así nos ahorramos repetir codigo, ya estaba implementado así en la otra rama

2022-03-30 16:29 UTC, JSnow11 commented on frontend/src/api/axios.ts
Ya estaba hecho en la rama de frontend, la he mergeado aquí

2022-03-30 16:30 UTC, JSnow11 approved these changes

2022-03-30 16:36 UTC, merged