#292 - task: Added CRUD for tags
ISPP-Eventia/eventus pull request #314
Opened 2022-04-20 00:39 UTC by laur2000

close #292

2022-04-20 13:55 UTC, pedalopon requested changes

2022-04-20 13:55 UTC, pedalopon commented on backend/src/main/java/com/eventus/backend/services/TagService.java
> +            throw new DuplicateKeyException("Tag already exists");
Esta excepción no se esta capturando en el catch que printea los errores. Deberías cambiarla a otro tipo de excepción

2022-04-20 13:55 UTC, pedalopon commented on backend/src/main/java/com/eventus/backend/services/TagService.java
> +            throw new DuplicateKeyException("Tag already associated with the event");
Aquí pasa igual

2022-04-20 13:55 UTC, pedalopon commented on backend/src/main/java/com/eventus/backend/services/TagService.java
> +                "Incorrect format for eventId");
Tambien los errores nuevos que metamos deberían estar en español para mantener la coherencia con frontend

2022-04-23 14:30 UTC, pedalopon approved these changes

2022-04-23 14:32 UTC, pabgonmon2 approved these changes
Approved.

2022-04-23 14:32 UTC, merged